 ## Problem Statement - 1
 
Write a function so that the columns of the output matrix are powers of the input vector. 
 
The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
 
 
HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde. 

In [30]:
import numpy as np

In [27]:
def vandermonde_matrix_genrator(vector, n, increasing = False):
    
    if increasing == False:
        op_matx = np.array([x**(n-1-i) for x in vector for i in range(n)]).reshape(vector.size,n)
    else:
        op_matx = np.array([x**i for x in vector for i in range(n)]).reshape(vector.size,n)
    
    return op_matx

input_vector = np.array([1,2,3,4,5])
num_col = 3
op_inc = vandermonde_matrix_genrator(input_vector,num_col,True)
op_dec = vandermonde_matrix_genrator(input_vector,num_col,False)
print('\n------------OUTPUT 1-------------\n')
print('Vander monde matrix in increasing oder \n',op_inc)
print('\n------------OUTPUT 2-------------\n')
print('Vander monde matrix in decreasing oder \n',op_dec)


------------OUTPUT 1-------------

Vander monde matrix in increasing oder 
 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]

------------OUTPUT 2-------------

Vander monde matrix in decreasing oder 
 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]


## Problem Statement - 2

Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of the given sequence is defined as follows: 
The moving average sequence has n-k+1 elements as shown below.  
The moving averages with k=4 of a ten-value sequence (n=10) is shown below:-

In [29]:
#i 1  2  3  4  5  6  7  8  9 10  
#===== == == == == == == == == == ==
#Input 10 20 30 40 50 60 70 80 90 100
#y1      25 = (10+20+30+40)/4
#y2      35 = (20+30+40+50)/4  
#y3      45 = (30+40+50+60)/4  
#y4      55 = (40+50+60+70)/4 
#y5      65 = (50+60+70+80)/4 
#y6      75 = (60+70+80+90)/4 
#y7      85 = (70+80+90+100)/4 
#Thus, the moving average sequence has n-k+1=10-4+1=7 values. 

#### Question: 
Write a function to find moving average in an array over a window:          
Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3

In [62]:
def moving_average(l,n,k):
    for i in range(n-k+1):
        avr = 0
        for j in range(i,i+k):
            avr += l[j]
            
        print('y' + str(i+1)+ ' =',avr//k)

arr = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
kth = 3
s = arr.size
moving_average(array,s,kth)
print(f'The moving average sequence has n - k + 1 = {s-kth+1} values')

y1 = 5
y2 = 4
y3 = 5
y4 = 6
y5 = 9
y6 = 28
y7 = 49
y8 = 72
y9 = 84
y10 = 93
y11 = 116
The moving average sequence has n - k + 1 = 11 values
